"""P16 — cross-language parity for error-column label inference.

``quantized.io.error_inference.infer_error_bindings_from_labels`` (built on
``error_label_candidates.py`` / ``error_label_classify.py``) and
``inferErrorBindingsFromLabels`` (``frontend/src/lib/errorRoles.ts``, built
on ``errorLabelCandidates.ts`` / ``errorLabelClassify.ts``) are two
independently maintained ports of the SAME rules -- nothing in the
toolchain enforces that they agree.

THIS FIXTURE IS GENERATED FROM THE TYPESCRIPT SOURCE OF TRUTH -- see
``frontend/src/lib/errorLabelParityFixture.gen.test.ts`` (both the
generator and the TypeScript half of this parity pin; regeneration
instructions are in its header comment). A diff between what this test
computes and the committed
``tests/fixtures/error_labels/parity_corpus.json`` means the TWO LANGUAGES
DISAGREE. THE FIX IS TO MAKE THEM AGREE -- port whichever side is wrong --
NEVER to regenerate the fixture to match a Python change: the fixture is
only ever regenerated by re-running the TypeScript.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from quantized.io.error_inference import infer_error_bindings_from_labels

FIXTURE_PATH = (
    Path(__file__).resolve().parent / "fixtures" / "error_labels" / "parity_corpus.json"
)


def _load_cases() -> list[dict[str, object]]:
    with open(FIXTURE_PATH, encoding="utf-8") as f:
        data = json.load(f)
    cases = data["cases"]
    assert isinstance(cases, list) and cases, "fixture must carry at least one case"
    return cases


@pytest.mark.parametrize(
    "case",
    _load_cases(),
    ids=[str(c["note"]) for c in _load_cases()],
)
def test_infer_error_bindings_matches_the_shared_fixture(case: dict[str, object]) -> None:
    labels = case["labels"]
    expected = case["bindings"]
    assert isinstance(labels, list)
    assert isinstance(expected, list)
    actual = [b.to_dict() for b in infer_error_bindings_from_labels(labels)]
    assert actual == expected, (
        f"infer_error_bindings_from_labels({labels!r}) should be {expected!r} per the "
        f"shared fixture ({case.get('note')!r}) -- check errorRoles.ts / "
        "errorLabelCandidates.ts / errorLabelClassify.ts stayed in sync, or that this "
        "fixture was regenerated from the TypeScript after a deliberate change there"
    )


def test_fixture_covers_both_bound_and_unbound_outcomes() -> None:
    """A fixture that only ever tested one outcome would not actually catch
    a drift in the other direction."""
    cases = _load_cases()
    bound = [c for c in cases if c["bindings"]]
    unbound = [c for c in cases if not c["bindings"]]
    assert bound, "fixture must include at least one case that produces a binding"
    assert unbound, "fixture must include at least one case that produces no binding"


def test_fixture_covers_asymmetric_and_x_axis_shapes() -> None:
    """The two shapes most likely to silently regress unnoticed (an
    asymmetric +/- half, and an x-axis target) must each appear at least
    once."""
    cases = _load_cases()
    sides = {b["side"] for c in cases for b in c["bindings"]}
    axes = {b["axis"] for c in cases for b in c["bindings"]}
    assert "+" in sides
    assert "x" in axes
