"""P16 review finding #7 — cross-language parity for the Import Wizard's
TWO-TIER error-binding suggestion narrowing.

``quantized.io.error_binding_suggestions.suggest_error_bindings_by_channel``
and ``suggestErrorBindings`` (``frontend/src/lib/importwizard.ts``) are two
independently maintained implementations of the SAME two-tier narrowing
rule -- nothing in the toolchain enforces that they agree. The label-level
inference underneath (``infer_error_bindings_from_labels``) already has a
parity fixture (``test_error_inference_parity_fixture.py``); this is the
same mechanism one layer up, for the demotion rule on top of it.

THIS FIXTURE IS GENERATED FROM THE TYPESCRIPT SOURCE OF TRUTH -- see
``frontend/src/lib/errorSuggestionParityFixture.gen.test.ts`` (both the
generator and the TypeScript half of this parity pin; regeneration
instructions and the deliberate-divergence scope note are in its header
comment). A diff between what this test computes and the committed
``tests/fixtures/error_labels/suggestion_parity_corpus.json`` means the TWO
LANGUAGES DISAGREE. THE FIX IS TO MAKE THEM AGREE -- port whichever side is
wrong -- NEVER to regenerate the fixture to match a Python change: the
fixture is only ever regenerated by re-running the TypeScript.

Every case in this fixture is DELIBERATELY chosen to be unaffected by the
Python port's own extra review-round fixes (x-name-axis matching, source/
target role restrictions) -- those are pinned separately, by dedicated
Python-only regression tests in ``test_io_error_binding_suggestions.py``,
never by this shared fixture.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from quantized.io.error_binding_suggestions import suggest_error_bindings_by_channel

FIXTURE_PATH = (
    Path(__file__).resolve().parent / "fixtures" / "error_labels" / "suggestion_parity_corpus.json"
)


def _load_cases() -> list[dict[str, object]]:
    with open(FIXTURE_PATH, encoding="utf-8") as f:
        data = json.load(f)
    cases = data["cases"]
    assert isinstance(cases, list) and cases, "fixture must carry at least one case"
    return cases


def _columns_from_case(case: dict[str, object]) -> list[dict[str, object]]:
    columns = case["columns"]
    assert isinstance(columns, list)
    out: list[dict[str, object]] = []
    for c in columns:
        assert isinstance(c, dict)
        col: dict[str, object] = {
            "index": c["index"], "name": c["name"], "unit": "", "role": c["role"],
        }
        if "effective_name" in c:
            col["effective_name"] = c["effective_name"]
        out.append(col)
    return out


@pytest.mark.parametrize(
    "case",
    _load_cases(),
    ids=[str(c["note"]) for c in _load_cases()],
)
def test_suggest_error_bindings_by_channel_matches_the_shared_fixture(
    case: dict[str, object],
) -> None:
    columns = _columns_from_case(case)
    expected = case["bindings"]
    assert isinstance(expected, list)
    actual = [b.to_dict() for b in suggest_error_bindings_by_channel(columns)]
    assert actual == expected, (
        f"suggest_error_bindings_by_channel({columns!r}) should be {expected!r} per the "
        f"shared fixture ({case.get('note')!r}) -- check importwizard.ts's "
        "suggestErrorBindings stayed in sync, or that this fixture was regenerated "
        "from the TypeScript after a deliberate change there"
    )


def test_fixture_covers_both_suggested_and_demoted_outcomes() -> None:
    """A fixture that only ever tested one outcome would not actually catch
    a drift in the other direction."""
    cases = _load_cases()
    suggested = [c for c in cases if c["bindings"]]
    demoted = [c for c in cases if not c["bindings"]]
    assert suggested, "fixture must include at least one case that produces a suggestion"
    assert demoted, "fixture must include at least one case that demotes to no suggestion"


def test_fixture_covers_the_x_axis_shape() -> None:
    """The rule-2 (explicit x-prefix) shape is the one most likely to
    silently regress unnoticed in the demotion logic."""
    cases = _load_cases()
    axes = {b["axis"] for c in cases for b in c["bindings"]}
    assert "x" in axes
