"""Origin export: a paired CSV + LabTalk ``.ogs`` script. Port of MATLAB
``+utilities/exportOriginScript.m``.

The ``.ogs`` script, when run in OriginPro, imports the accompanying CSV, sets
column designations (X / Y / yErr by label), long names + units, and optionally
builds a graph — a maintainable alternative to writing binary ``.opju`` files.

Pure layer: ``format_origin_script`` returns ``(csv_text, ogs_text)`` (no disk
I/O). The ``created`` timestamp is injected by the caller so the function stays
deterministic (the route passes the wall-clock time; tests pass a fixed value).
"""

from __future__ import annotations

import re
from typing import Any

import numpy as np

from quantized.datastruct import DataStruct

__all__ = ["format_origin_project_script", "format_origin_script"]

_ERR_KEYWORDS = ("err", "dr", "std", "sigma")


def _meta_get(meta: dict[str, Any], *keys: str, default: Any = None) -> Any:
    """First present, non-empty metadata value among ``keys`` (snake/camel)."""
    for key in keys:
        val = meta.get(key)
        if val not in (None, ""):
            return val
    return default


def _escape_lt(text: str) -> str:
    """Escape double-quotes for a LabTalk string literal."""
    return text.replace('"', '\\"')


def _sanitize(name: str) -> str:
    """LabTalk-safe identifier: non-word chars -> underscore (MATLAB \\W)."""
    return re.sub(r"\W", "_", name)


def _is_err_label(label: str) -> bool:
    low = label.lower()
    return any(kw in low for kw in _ERR_KEYWORDS)


def format_origin_script(
    data: DataStruct,
    *,
    csv_name: str = "data.csv",
    book_name: str = "",
    sheet_name: str = "",
    log_x: bool = False,
    log_y: bool = False,
    make_graph: bool = True,
    created: str = "",
    book_long_name: str = "",
) -> tuple[str, str]:
    """Return ``(csv_text, ogs_text)`` for ``data``. Port of exportOriginScript.

    ``csv_name`` is the CSV filename the script references (``impASC``).
    ``book_name``/``sheet_name`` default to the source filename in metadata,
    then ``"data"``; both are sanitized to LabTalk identifiers.
    """
    meta = dict(data.metadata)
    source = _meta_get(meta, "source", "filepath", "filename", default="")
    base = str(source).replace("\\", "/").rsplit("/", 1)[-1].rsplit(".", 1)[0]
    book = _sanitize(book_name or base or "data")
    sheet = _sanitize(sheet_name or book)

    x_name = str(_meta_get(meta, "x_column_name", "xColumnName", default="X"))
    x_unit = str(_meta_get(meta, "x_column_unit", "xColumnUnit", default=""))

    labels = list(data.labels)
    units = list(data.units)
    time = np.asarray(data.time, dtype=float)
    values = np.asarray(data.values, dtype=float)

    # ── CSV: header, units, then %.10g data rows ──
    csv_lines = [
        ",".join([x_name, *labels]),
        ",".join([x_unit, *units]),
    ]
    for r in range(values.shape[0]):
        cells = [f"{time[r]:.10g}"]
        cells.extend(f"{values[r, c]:.10g}" for c in range(values.shape[1]))
        csv_lines.append(",".join(cells))
    csv_text = "\n".join(csv_lines) + "\n"

    # ── LabTalk (.ogs) script ──
    o: list[str] = [
        "// LabTalk script generated by quantized_matlab",
        f"// Date: {created}",
        "",
        "// Import data",
        f'newbook name:="{book}" sheet:=1;',
        *([f'page.longname$ = "{_escape_lt(book_long_name)}";'] if book_long_name else []),
        f'wks.name$ = "{sheet}";',
        f'impASC fname:="{csv_name}" options.SkipRows.Count:=2;',
        "",
        "// Column designations and labels",
        "wks.col1.type = 4;  // X",
        f'wks.col1.lname$ = "{_escape_lt(x_name)}";',
        f'wks.col1.unit$ = "{_escape_lt(x_unit)}";',
    ]
    for k, label in enumerate(labels):
        cn = k + 2
        unit = units[k] if k < len(units) else ""
        if _is_err_label(label):
            o.append(f"wks.col{cn}.type = 3;  // yErr")
        else:
            o.append(f"wks.col{cn}.type = 1;  // Y")
        o.append(f'wks.col{cn}.lname$ = "{_escape_lt(label)}";')
        o.append(f'wks.col{cn}.unit$ = "{_escape_lt(unit)}";')

    if make_graph:
        o += ["", "// Create graph", "plotxy iy:=(1,2) plot:=201 ogl:=[<new>];"]
        if log_x:
            o.append("layer.x.type = 1;  // Log X")
        if log_y:
            o.append("layer.y.type = 1;  // Log Y")
        x_title = x_name + (f" ({x_unit})" if x_unit else "")
        o.append(f'xb.text$ = "{_escape_lt(x_title)}";')
        if len(labels) == 1:
            y_unit = units[0] if units else ""
            y_title = labels[0] + (f" ({y_unit})" if y_unit else "")
            o.append(f'yl.text$ = "{_escape_lt(y_title)}";')

    o += ["", "// Done"]
    ogs_text = "\n".join(o) + "\n"
    return csv_text, ogs_text


def format_origin_project_script(
    items: list[tuple[DataStruct, str]],
    *,
    created: str = "",
    make_graph: bool = False,
) -> tuple[list[tuple[str, str]], str]:
    """Multi-book export: one LabTalk ``.ogs`` importing N CSVs into N books.

    ``items`` is ``[(dataset, book_name), …]`` (an empty name falls back to the
    dataset's ``origin_book`` metadata, then ``dataN``). Returns
    ``([(csv_name, csv_text), …], ogs_text)`` — the script recreates every
    workbook with designations, long names, units, and the book display title
    (``page.longname$``) when the dataset carries one.
    """
    if not items:
        raise ValueError("format_origin_project_script needs at least one dataset")
    csvs: list[tuple[str, str]] = []
    sections: list[str] = [
        "// LabTalk project script generated by quantized",
        f"// Date: {created}",
        f"// Books: {len(items)}",
    ]
    used: set[str] = set()
    for i, (ds, name) in enumerate(items):
        meta = dict(ds.metadata)
        book = _sanitize(str(name or meta.get("origin_book", "") or f"data{i + 1}"))
        base = book
        n = 1
        while book in used:
            n += 1
            book = f"{base}{n}"
        used.add(book)
        long_name = str(meta.get("origin_book_long", "") or "")
        csv_name = f"{book}_data.csv"
        csv_text, ogs_text = format_origin_script(
            ds,
            csv_name=csv_name,
            book_name=book,
            sheet_name=book,
            make_graph=make_graph,
            created=created,
            book_long_name=long_name if long_name != book else "",
        )
        csvs.append((csv_name, csv_text))
        body = ogs_text.splitlines()
        # drop the per-script header comment lines (kept once at the top)
        while body and body[0].startswith("//"):
            body.pop(0)
        sections += ["", f"// ---- Book {i + 1}: {book} ----", *body]
    return csvs, "\n".join(sections) + "\n"
