// The KaTeX half of the equation preview's lazy seam (audit P2.7 stretch).
// This module is reached ONLY through lib/katexLazy.ts's dynamic import(), so
// KaTeX, its stylesheet and the fonts that stylesheet pulls in ship in a chunk
// fetched the first time a preview has something to draw -- never at startup.
// `architecture.test.ts` pins both halves: nothing else value-imports `katex`,
// and nothing imports this module statically.
//
// The stylesheet is a static import HERE (not a second dynamic import beside
// the library's) so Vite attaches it to this chunk and preloads it with it.
//
// `renderTex` returns a string or null and never throws: KaTeX's own parse
// errors (`throwOnError`) come back as null, so the preview shows nothing
// rather than KaTeX's red error text. Its input is generated by
// lib/equationLatex.ts from a closed grammar (no user text passes through
// verbatim, and `trust` stays off), so the HTML is KaTeX's own markup.

import katex from "katex";
import type { KatexOptions } from "katex";
import "katex/dist/katex.min.css";

const OPTIONS: KatexOptions = { throwOnError: true, strict: "ignore", output: "html", trust: false };

/** KaTeX HTML for a LaTeX string, or null when KaTeX refuses it. */
export function renderTex(tex: string): string | null {
  try {
    return katex.renderToString(tex, OPTIONS);
  } catch {
    return null;
  }
}
