// PRIMARY_SOFTWARE_AUDIT_PLAN P2.6 — rename ONE categorical level in place.
//
// A level's identity is its CODE (see lib/categorical.ts and store/
// levelOrder.ts's "codes are identity" header): rows hold codes, formula
// literals like `A==1` bind to codes, and `level_order` lists codes. So a
// rename only ever rewrites one string in `cat_levels[channel]` — the codes,
// the stored order and every formula keep meaning exactly what they meant.
//
// The one label-keyed consumer is a Recode column built on this channel: its
// mapping groups name SOURCE levels by string (`RecodeGroup.from`), so a
// rename that left them alone would silently drop the renamed level out of
// its group. Those references are rewritten here, in the same edit.
//
// Pure: DataStruct + formulas in, the next DataStruct + formulas (or a
// one-sentence refusal) out. The store (store/levelRename.ts) owns undo, the
// re-derived guard, and the formula recompute.

import { categoricalLevels, labelForCode } from "./categorical";
import { channelLetter } from "./formula";
import type { RecodeSpec } from "./recode";
import type { ComputedColumn, DataStruct } from "./types";

export type LevelRenameResult =
  | {
      ok: true;
      /** False when the trimmed name equals the current one — nothing to do. */
      changed: boolean;
      oldLabel: string;
      newLabel: string;
      data: DataStruct;
      formulas: ComputedColumn[] | undefined;
    }
  | { ok: false; reason: string };

export const COMPUTED_LEVEL_NOTICE = "This column's levels come from its formula; edit the recode instead.";

/** Rewrite one recode's mapping so every group naming `oldLabel` names
 *  `newLabel` — or names BOTH when another code still carries `oldLabel` (a
 *  table may legitimately hold a repeated label after a merge-by-name). */
function renameInRecode(spec: RecodeSpec, oldLabel: string, newLabel: string, oldSurvives: boolean): RecodeSpec {
  const groups = spec.mapping.groups.map((g) => {
    if (!g.from.includes(oldLabel)) return g;
    const from = oldSurvives ? [...g.from, newLabel] : g.from.map((s) => (s === oldLabel ? newLabel : s));
    return { ...g, from: [...new Set(from)] };
  });
  return { ...spec, mapping: { ...spec.mapping, groups } };
}

/** Re-attach a COMPUTED column's `level_order` after the post-rename
 *  recompute when that column's per-row codes and table length came back
 *  unchanged — then every stored code still names the same level, even if a
 *  pass-through label changed (which `carryComputedLevelOrder`'s identical-
 *  table rule would refuse). `baseCount` = the dataset's non-computed columns. */
export function carryOrderAcrossRename(before: DataStruct, after: DataStruct, baseCount: number): DataStruct {
  const prior = before.level_order;
  if (!prior) return after;
  const carried: Record<number, number[]> = { ...(after.level_order ?? {}) };
  let changed = false;
  for (const [key, codes] of Object.entries(prior)) {
    const ch = Number(key);
    if (ch < baseCount || ch in carried) continue;
    if (before.cat_levels?.[ch]?.length !== after.cat_levels?.[ch]?.length) continue;
    if (!before.values.every((row, i) => Object.is(row[ch], after.values[i]?.[ch]))) continue;
    carried[ch] = [...codes];
    changed = true;
  }
  return changed ? { ...after, level_order: carried } : after;
}

export function renameLevelIn(
  data: DataStruct,
  formulas: ComputedColumn[] | undefined,
  channel: number,
  code: number,
  name: string,
): LevelRenameResult {
  // A formula/recode column's level table is regenerated by every recompute,
  // so a rename written into it would vanish on the next one.
  if (channel >= data.labels.length - (formulas?.length ?? 0)) return { ok: false, reason: COMPUTED_LEVEL_NOTICE };
  const levels = categoricalLevels(data, channel);
  if (!levels) return { ok: false, reason: "Only a categorical column's levels can be renamed." };
  const oldLabel = labelForCode(levels, code);
  if (oldLabel == null) return { ok: false, reason: "That level is not in the column's level table." };
  const newLabel = name.trim();
  if (!newLabel) return { ok: false, reason: "A level name can't be empty." };
  if (newLabel === oldLabel) return { ok: true, changed: false, oldLabel, newLabel, data, formulas };
  if (levels.includes(newLabel)) {
    return { ok: false, reason: `A level named "${newLabel}" already exists in this column.` };
  }
  const nextLevels = levels.map((l, i) => (i === code ? newLabel : l));
  const next: DataStruct = { ...data, cat_levels: { ...data.cat_levels, [channel]: nextLevels } };
  const letter = channelLetter(channel);
  const oldSurvives = nextLevels.includes(oldLabel);
  const nextFormulas = formulas?.map((f) =>
    f.recode && f.recode.sourceLetter === letter
      ? { ...f, recode: renameInRecode(f.recode, oldLabel, newLabel, oldSurvives) }
      : f,
  );
  return { ok: true, changed: true, oldLabel, newLabel, data: next, formulas: nextFormulas };
}
